### ISSUE TITLE
Dizzy WARNINGs: "Failed to parse component: java.lang.NullPointerException: null"

### ISSUE THREAD

**Issue by Rortenfeat** [SL0ANE/ChatBox#2]
日志每秒都要弹不下二十条这个警告：
`[hh:mm:ss] [Server thread/WARN]: Failed to parse component: java.lang.NullPointerException: null`
虽然性能影响不到，但是盯着日志的时候啥都看不清还是挺头疼的。

我找到的解决办法是把需要解析成空JSON文本的空字符串变成合规JSON，
比如`generic:text/create_space/negative/do`和`generic:text/create_space/positive/do`中的
`data modify storage generic:main TextOutput set value ''`
改成
`data merge storage generic:main {TextOutput:'{"text":""}'}`
然后至少它不会刷屏了。

然后其它的地方我懒得找了。
怎么说，
万一您也懒得改呢。
总之，问题不大。
:)

**Comment by SL0ANE** [comment]
感谢反馈 刚刚在清另外一个问题，v1.1.0版本的包会让世界保存变得很慢
现在搞好了 顺便把这个一起解决了
